version: '2'
services:
  db:
    image: mysql:5.6
    environment:
      MYSQL_ROOT_PASSWORD: password
    volumes:
      - ./docker/mysql:/var/lib/mysql

  web:
    build: .
    volumes:
      - .:/usr/src/myapp
    ports:
      - '3000:3000'
    command: bundle exec rails s -p 3000 -b '0.0.0.0'
    links:
      - db
      - redis

  redis:
    image: redis:3.0.6
    
